[package]
name = "scarlite"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
description = "Scarlite browser project and Phos rendering engine"
repository = "https://github.com/saudaljuaid/Scarlite"
readme = "README.md"

[dependencies]
base64 = "0.22"
encoding_rs = "0.8.35"
harfrust = "0.13.3"
image = { version = "0.25.8", default-features = false, features = ["png", "jpeg"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12"] }
unicode-segmentation = "1.12.0"
unicode-bidi = "0.3.18"
unicode-linebreak = "0.1.5"
ttf-parser = "0.25.1"
webpki-roots = "1"

[dev-dependencies]
roxmltree = "0.21"
serde_json = "1"

[lib]
name = "phos"
path = "src/lib.rs"

[[bin]]
name = "scarlite"
path = "src/main.rs"
